INSTALL_CMD = cp
TARGET = i586-pc-quest
TOOLCHAIN-INSTALL-DIR = $(HOME)/bin/cross
CC = $(TARGET)-gcc
LD = $(TARGET)-ld
AR = $(TARGET)-ar
LIB_DEST = $(TOOLCHAIN-INSTALL-DIR)/$(TARGET)/lib
INC_DEST = $(TOOLCHAIN-INSTALL-DIR)/$(TARGET)/include
